CREATE DATABASE `savethechildren` /*!40100 DEFAULT CHARACTER SET utf8 */;
DROP TABLE IF EXISTS USERS_INFO


-- Users
CREATE TABLE USERS_INFO
(
	USER_ID varchar(22) NOT NULL COMMENT 'USER_ID',
	USER_NAME varchar(50) COMMENT 'USER_NAME',
	ID int(22) NOT NULL AUTO_INCREMENT COMMENT 'ID',
	CREATED_DATE date NOT NULL  COMMENT 'CREATED_DATE',
	MODIFIED_DATE date NOT NULL COMMENT 'MODIFIED_DATE',
	FIRST_TIME_LOGIN INT COMMENT 'FIRST_TIME_LOGIN',
	CREATED_USER_NAME varchar(50) COMMENT 'CREATED_USER_NAME',
	MODIFIED_USER_NAME varchar(50) COMMENT 'MODIFIED_USER_NAME',
	DESCRIPTION varchar(500) COMMENT 'DESCRIPTION',
	PASSWORD varchar(50) NOT NULL COMMENT 'PASSWORD',
	PRIMARY KEY (ID)
) COMMENT = 'USERS_INFO';

CREATE TABLE SCHOOL_UPDATING
(
	ID int(10) NOT NULL AUTO_INCREMENT COMMENT 'ID',
	SCHOOL_CODE VARCHAR(200) NOT NULL COMMENT 'SCHOOL_CODE',
    VILLAGE_NAME  VARCHAR(200) NOT NULL COMMENT 'VILLAGE_NAME',
    TOWNSHIP  VARCHAR(200) NOT NULL COMMENT 'TOWNSHIP',
    ACTIVITY_TYPE int(10) NOT NULL  COMMENT 'ACTIVITY_TYPE',
    RECORD_STATUS int(10) NOT NULL  COMMENT 'RECORD_STATUS',
    MONITORING_DATE date NOT NULL COMMENT 'MODIFIED_DATE',
    CREATED_DATE date NOT NULL  COMMENT 'CREATED_DATE',
	MODIFIED_DATE date NOT NULL COMMENT 'MODIFIED_DATE',
    CREATED_USER_NAME varchar(50) COMMENT 'CREATED_USER_NAME',
	MODIFIED_USER_NAME varchar(50) COMMENT 'MODIFIED_USER_NAME',
	PRIMARY KEY (ID)
) COMMENT = 'SCHOOL_UPDATING';

CREATE TABLE SCHOOL_UPDATING_SURVEY
(
	ID int(10) NOT NULL AUTO_INCREMENT COMMENT 'ID',
	TYPE_ID int(10) NOT NULL  COMMENT 'TYPE_ID',
	LABEL VARCHAR(500) NOT NULL COMMENT 'LABEL',
    MALE_COUNT int(10) NOT NULL  COMMENT 'MALE_COUNT',
    FEMALE_COUNT int(10) NOT NULL  COMMENT 'FEMALE_COUNT',
    PARENT_ID int(10) NOT NULL  COMMENT 'PARENT_ID',
    CREATED_DATE date NOT NULL  COMMENT 'CREATED_DATE',
     RECORD_STATUS int(10) NOT NULL  COMMENT 'RECORD_STATUS',
	MODIFIED_DATE date NOT NULL COMMENT 'MODIFIED_DATE',
    CREATED_USER_NAME varchar(50) COMMENT 'CREATED_USER_NAME',
	MODIFIED_USER_NAME varchar(50) COMMENT 'MODIFIED_USER_NAME',
	PRIMARY KEY (ID)
) COMMENT = 'SCHOOL_UPDATING_SURVEY';

CREATE TABLE SCHOOL_UPDATING_HISTORY
(
	ID int(10) NOT NULL AUTO_INCREMENT COMMENT 'ID',
	TYPE_ID int(10) NOT NULL  COMMENT 'TYPE_ID',
	LABEL VARCHAR(500) NOT NULL COMMENT 'LABEL',
    MALE_COUNT int(10) NOT NULL  COMMENT 'MALE_COUNT',
    FEMALE_COUNT int(10) NOT NULL  COMMENT 'FEMALE_COUNT',
    PARENT_ID int(10) NOT NULL  COMMENT 'PARENT_ID',
    MONITORING_DATE date NOT NULL COMMENT 'MODIFIED_DATE',
    MODIFIED_USER_NAME varchar(100) COMMENT 'MODIFIED_USER_NAME',
	PRIMARY KEY (ID)
) COMMENT = 'SCHOOL_UPDATING_HISTORY';

CREATE TABLE SCHOOL_MONITORING
(
	ID int(10) NOT NULL AUTO_INCREMENT COMMENT 'ID',
	SCHOOL_CODE VARCHAR(200) NOT NULL COMMENT 'SCHOOL_CODE',
    VILLAGE_NAME  VARCHAR(200) NOT NULL COMMENT 'VILLAGE_NAME',
    TOWNSHIP  VARCHAR(200) NOT NULL COMMENT 'TOWNSHIP',
    ACTIVITY_TYPE int(10) NOT NULL  COMMENT 'ACTIVITY_TYPE',
    RECORD_STATUS int(10) NOT NULL  COMMENT 'RECORD_STATUS',
    MONITORING_DATE date NOT NULL COMMENT 'MODIFIED_DATE',
    CREATED_DATE date NOT NULL  COMMENT 'CREATED_DATE',
	MODIFIED_DATE date NOT NULL COMMENT 'MODIFIED_DATE',
    CREATED_USER_NAME varchar(50) COMMENT 'CREATED_USER_NAME',
	MODIFIED_USER_NAME varchar(50) COMMENT 'MODIFIED_USER_NAME',
    ESTABLISHED_DATE date NOT NULL COMMENT 'ESTABLISHED_DATE',
    BUILDING_SIZE VARCHAR(250) NOT NULL COMMENT 'BUILDING_SIZE',
    COMPOUND_SIZE VARCHAR(250) NOT NULL COMMENT 'COMPOUND_SIZE',
    DISTANCE_TYPE_SERVICE_TOWN INT(10) NOT NULL COMMENT 'DISTANCE_TYPE_SERVICE_TOWN',
    DISTANCE_TYPE_SERVICE_SCHOOL INT(10) NOT NULL COMMENT 'DISTANCE_TYPE_SERVICE_SCHOOL',
    MEETING_TYPE INT(10) NOT NULL COMMENT 'MEETING_TYPE',
    REVOLVE_FUND DOUBLE(15,5) NOT NULL COMMENT 'REVOLVE_FUND',
    MONTHLY_REVOLVE_FUND DOUBLE(15,5) NOT NULL COMMENT 'MONTHLY_REVOLVE_FUND',
    PARENT_FEE DOUBLE(15,5) NOT NULL COMMENT 'PARENT_FEE',
    OTHER_INCOME DOUBLE(15,5) NOT NULL COMMENT 'OTHER_INCOME',
    MONTHLY_INCOME DOUBLE(15,5) NOT NULL COMMENT 'MONTHLY_INCOME',
    CAREGIVER_SALARY DOUBLE(15,5) NOT NULL COMMENT 'CAREGIVER_SALARY',
    ISSUE_PROBLEM VARCHAR(500) NOT NULL COMMENT 'ISSUE_PROBLEM',
    COMPLETE_RESOLVE INT(1) NOT NULL COMMENT 'COMPLETE_RESOLVE',
    OPEN_CLOSE INT(1) NOT NULL COMMENT 'OPEN_CLOSE',
    ECCD_APE_STANDARD VARCHAR(250) NOT NULL COMMENT 'ECCD_APE_STANDARD',
	PRIMARY KEY (ID)
) COMMENT = 'SCHOOL_MONITORING';

CREATE TABLE SCHOOL_SUPPORT
(
	ID int(10) NOT NULL AUTO_INCREMENT COMMENT 'ID',
	RECORD_STATUS NUMERIC(1) NOT NULL COMMENT 'RECORD_STATUS',
	PARENTID  INT(10) NOT NULL COMMENT 'PARENTID',
	SCHOOL_CODE VARCHAR(250) NOT NULL COMMENT 'SCHOOL_CODE',
    SUPPORT_TYPE INT(10) NOT NULL COMMENT 'SUPPORT_TYPE',
    SUPPORT_VALUE_LBL VARCHAR(100) NOT NULL COMMENT 'SUPPORT_VALUE_LBL',
    SUPPORTER_NAME VARCHAR(550) NOT NULL COMMENT 'SUPPORTER_NAME',
    PRIMARY KEY (ID)
) COMMENT = 'SCHOOL_SUPPORT';

CREATE TABLE SCHOOL_MONITORING_SUPPORTER
(
	ID int(10) NOT NULL AUTO_INCREMENT COMMENT 'ID',
	RECORD_STATUS NUMERIC(1) NOT NULL COMMENT 'RECORD_STATUS',
	PARENTID  INT(10) NOT NULL COMMENT 'PARENTID',
    SUPPORTER_TYPE INT(2) NOT NULL COMMENT 'SUPPORTER_TYPE',
    SUPPORTER_LBL VARCHAR(100) NOT NULL COMMENT 'SUPPORTER_LBL',
    PRIMARY KEY (ID)
) COMMENT = 'SCHOOL_MONITORING_SUPPORTER';

CREATE TABLE SCHOOL_MONITORING_SURVEY
(
	ID int(10) NOT NULL AUTO_INCREMENT COMMENT 'ID',
	TYPE_ID int(10) NOT NULL  COMMENT 'TYPE_ID',
	LABEL VARCHAR(500) NOT NULL COMMENT 'LABEL',
    MALE_COUNT int(10) NOT NULL  COMMENT 'MALE_COUNT',
    FEMALE_COUNT int(10) NOT NULL  COMMENT 'FEMALE_COUNT',
    PARENT_ID int(10) NOT NULL  COMMENT 'PARENT_ID',
    CREATED_DATE date NOT NULL  COMMENT 'CREATED_DATE',
     RECORD_STATUS int(10) NOT NULL  COMMENT 'RECORD_STATUS',
	MODIFIED_DATE date NOT NULL COMMENT 'MODIFIED_DATE',
    CREATED_USER_NAME varchar(50) COMMENT 'CREATED_USER_NAME',
	MODIFIED_USER_NAME varchar(50) COMMENT 'MODIFIED_USER_NAME',
	PRIMARY KEY (ID)
) COMMENT = 'SCHOOL_MONITORING_SURVEY';


CREATE TABLE SCHOOL_MONITORING_HISTORY
(
	ID int(10) NOT NULL AUTO_INCREMENT COMMENT 'ID',
	TYPE_ID int(10) NOT NULL  COMMENT 'TYPE_ID',
	LABEL VARCHAR(500) NOT NULL COMMENT 'LABEL',
    MALE_COUNT int(10) NOT NULL  COMMENT 'MALE_COUNT',
    FEMALE_COUNT int(10) NOT NULL  COMMENT 'FEMALE_COUNT',
    PARENT_ID int(10) NOT NULL  COMMENT 'PARENT_ID',
    MONITORING_DATE date NOT NULL COMMENT 'MODIFIED_DATE',
    MODIFIED_USER_NAME varchar(100) COMMENT 'MODIFIED_USER_NAME',
    RECORD_STATUS NUMERIC(1) NOT NULL COMMENT 'RECORD_STATUS',
	PRIMARY KEY (ID)
) COMMENT = 'SCHOOL_MONITORING_HISTORY';


ALTER TABLE USERS_INFO MODIFY PASSWORD VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL COMMENT 'PASSWORD';
alter table users_info add GENDER  numeric(1) NOT NULL COMMENT 'GENDER';
alter table users_info add ROLE  numeric(1) NOT NULL COMMENT 'ROLE';
alter table SCHOOL_UPDATING_HISTORY add RECORD_STATUS  numeric(1) NOT NULL COMMENT 'RECORD_STATUS';
alter table users_info add ADDRESS  varchar(500) NOT NULL COMMENT 'ADDRESS';
alter table users_info add POSITION  varchar(350) NOT NULL COMMENT 'POSITION';
alter table users_info add STATUS  numeric(1)  NOT NULL COMMENT 'STATUS';

alter table school_monitoring add LATRINE_NUM  INT(10) NOT NULL COMMENT 'LATRINE_NUM';
alter table school_monitoring add GETWATER  numeric(1) NOT NULL COMMENT 'GETWATER';
alter table school_monitoring add GENERAL_EXPENSE double(15,5) not null COMMENT 'GENERAL_EXPENSE';
alter table school_monitoring add TOTAL_EXPENSE double(15,5) not null COMMENT 'TOTAL_EXPENSE';
alter table school_monitoring add MONTHLY_BALANCE double(15,5) not null COMMENT 'MONTHLY_BALANCE';
alter table SCHOOL_MONITORING_SURVEY add DESCRIPTION  varchar(800) NOT NULL COMMENT 'DESCRIPTION';


Insert into `users_info` (`USER_ID`,`USER_NAME`,`ID`,`CREATED_DATE`,`MODIFIED_DATE`,`FIRST_TIME_LOGIN`,`CREATED_USER_NAME`,`MODIFIED_USER_NAME`,`DESCRIPTION`,`PASSWORD`,
`GENDER`,`ROLE`,`ADDRESS`,`POSITION`,`STATUS`)
 VALUES ('admin','Administrator','1','2016-08-08 09:56:11','2016-08-08 09:56:11','1','','','',AES_ENCRYPT('root', '01234567890'),'0','2','','',1);